name:                jifs
version:             0.1.0.0
github:              "github.com/dedifferentiator/jifs"
license:             GPL-2.0
author:              "dedifferentiator"
maintainer:          "dedifferentiator"
copyright:           "2020 yohashi, dedifferentiator"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <github.com/dedifferentiator/jifs/blob/master/README.md>
dependencies:
- base >= 4.7 && < 5
- unix
- bytestring
- clock
- time
- resourcet
- libfuse3 >= 0.1
- aeson
- filepath
- directory

library:
  source-dirs: src

executables:
  jifs:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - linux-xattr >= 0.1
    - jifs

tests:
  jifs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jifs
